config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users

  get 'main' ,to: 'users#main'
  post 'main', to: 'users#login'
  get 'feed', to: 'users#feed'
  get 'register', to:'users#register'
  get '/profile/:name', to: 'users#profile', as: "profile"
  post '/profile/:name/follow', to: 'users#follow' ,as: "follow_user"
  post '/profile/:name/unfollow', to: 'users#unfollow' ,as: "unfollow_user"

  get 'new_post', to:'posts#new_post'
  post 'createPost', to: 'posts#createPost'

  post 'feed/:post_id/like', to: 'posts#like', as: "like_post"
  post 'feed/:post_id/unlike', to: 'posts#unlike',as: "unlike_post"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,:name ,presence: true ,uniqueness: true
	validates :password_digest ,presence: true 
	#length: { in:8..15}
	has_secure_password
	validates_confirmation_of :password_digest, :message => "password should match password"
	has_many :posts ,dependent: :destroy
	has_many :likes ,dependent: :destroy

	has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow" 
    has_many :followers, through: :follower_follows, source: :follower
    has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"
    has_many :followees, through: :followee_follows, source: :followee
   	
   	
    def get_feed_post
	   posts = []
	   self.followees.each do |f|
	     f.posts.each do |p|
	       posts.push(p)
	     end
	   end
	   return posts.sort().reverse
   	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include MainConcern
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :is_logged_in, only: %i[feed profile]
  def main
    session[:user_id] = nil
  end

  def login
    @email = params[:email]
    @pass = params[:password]
    @user = User.find_by(email:@email)
    respond_to do |format|
      unless(@user.present? && @user.authenticate(@pass))
        format.html { redirect_to main_path , alert: "Email/password not valid" }
      else
        session[:user_id] = @user.id
        format.html{ redirect_to feed_path, notice: "Login successfully"}
      end
    end
    #@user.pass == params[:pass]
    #unless(@user.present? && @user.authenticate(@pass))
    #  redirect_to main_path , alert: "Email/password not valid"
    #else
    #  session[:user_id] = @user.id
    #  redirect_to show3_path, notice: "Login successfully"
    #end
  end

  def register
    @user = User.new
  end

#  def feed #should not be in model
#    @user = User.find(session[:user_id])
#    @posts = []
#    @user.followees.each do |f|
#      f.posts.each do |p|
#        @posts.push(p)
#      end
#    end
#    @posts = @posts.sort().reverse
#  end

  def feed
    @user = User.find(session[:user_id])
    @posts = @user.get_feed_post 
  end

  def profile
    @user = User.find(session[:user_id])
    @profile_user = User.find_by(name:params[:name])
    unless(@profile_user.present?)
      redirect_to feed_path ,alert: "Could not find this user."
    end
  end

  def follow
    profile_user = User.find_by(name:params[:name])
    Follow.create(follower_id:session[:user_id],followee_id:profile_user.id)
    redirect_to profile_path(params[:name]) ,notice: "You just follow " + profile_user.name
  end

  def unfollow
    profile_user = User.find_by(name:params[:name])
    Follow.find_by(follower_id:session[:user_id],followee_id:profile_user.id).destroy
    redirect_to profile_path(params[:name])  ,notice: "You just unfollow " + profile_user.name
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to "/main", notice: "User was successfully created." }
        format.json { render :main, status: :created , location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      #@user = User.find(session[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :email ,placeholder: 'email'
    = f.input :name 
    = f.input :password, label: 'Password',hint:'8-15 characters'
    = f.input :password_confirmation, label: 'Password Confirmation'

  .form-actions
    = f.button :submit

app/views/users/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  :javascript
    function searchUser() {
      var profileUser = document.getElementById("searchText");
      console.log("Hello");
      console.log(profileUser.value);
      window.location.href = "/profile/"+profileUser.value;
      //window.location.history.push("/profile/f");
      }
  .container-fluid
    %a.navbar-brand{:href => "/feed"}
      %img.d-inline-block.aligSn-text-top{:alt => "", :height => "24", :src => "https://cdn-icons-png.flaticon.com/512/1012/1012600.png", :width => "30"}
      tDUCK
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %form.d-flex.me-2 
          %input.form-control.w-75.me-2#searchText{"aria-label" => "Search", :placeholder => "Search for user", :type => "search"}/
          %button.btn.btn-outline-success{:onclick => "searchUser()",:type => "button"} Search
      .d-flex.justify-content-end
        %a.btn.btn-info.me-2{:href => "/new_post"}  Post
        %a.btn.btn-outline-secondary{:href => main_path}  Logout

%br
%br

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/feed.html.haml
- flash.each do |type, msg|
  .alert.alert-info
    = msg
= render 'nav'
- @posts.each do |post| 
  - profile_user_name = User.find(post.user_id).name
  .card.mt-4{:style => "width: 50vw;"}
    .card-body.cardPost
      %h5.card-title
        %a.card-link.card-link-feed{:href => "/profile/#{profile_user_name}",:method =>"get",:style => "font-size:25px"}= profile_user_name
      %h6.card-subtitle.mb-2.text-muted= post.created_at.to_formatted_s(:short)
      %pCard.card-text.fst-italic= post.msg
      %br
      - if post.user_likes.include?(@user)
        = button_to "Unlike", unlike_post_path(post.id) , method: "POST",class:"btn btn-primary unlike-btn mt-2"
      - else
        = button_to "Like", like_post_path(post.id) , method: "POST" ,class:"btn btn-secondary  like-btn mt-2"
      - if post.likes.count != 0 
        %button.btn.btn-primary.btn-showUser.mt-2.showUsers{"data-bs-target" => "#Like", "data-bs-toggle" => "modal", :type => "button","dataModal": post.user_likes.to_json}
          -#----------------number of like------------------
          = post.likes.count.to_s + " Likes"

.modal.fade{id: "Like",role: "modal","aria-hidden" => "true","taria-labelledby" => "exampleModalLabel",   :tabindex => "-1"}
  .modal-dialog.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h5#exampleModalLabel.w-100.modal-title.text-center ❤
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type  => "button"}
      .modal-body
        .div#mo_body{:style => "font-size:25px"}
          -# - post.user_likes.each do |user|
          -#%a.card-link-feed{:href => "profile/#{user.name}",:method => "get",:style=> " font-size:25px"}
          -#/    = user.name
          -#/    %br
          -#/    %br
    
%br

:javascript
  $(".showUsers").click(function(){
    $("#mo_body").empty();
    var userJson = $(this).attr("dataModal");
    var userObject = jQuery.parseJSON(userJson);
    userObject.forEach((user) =>{
      //var link = document.createElement("a");
      var link = `<a class = "card-link-feed" href ="/profile/${user.name}"> ${user.name} </a> <br><br>`;
      $("#mo_body").append(link);   
    })
    //var myModal = new bootstrap.Modal(document.getElementById(`Like`, {}));
  });
  //$(".btn-close").click(function(){
  //  $('.modal').hide();
  //});
/
/%table
/  %thead
/    %tr
/      %th Post_by
/      %th Message
/      %th Create_at
/      %th{:colspan => "3"}
/  %tbody 
/    - @posts.each do |post|
/      %tr
/        %td= post.user_id
/        %td= post.msg
/        %td= post.created_at.to_formatted_s(:short)
/        -#%td= link_to 'Edit', edit_post_path(post.id)
/        -#%td= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?'}
/= button_to main_path do 
/  = 'Log out'
/  - flash.alert= "Bye Bye"
/  - method: => "get"

/hw -> write script to show proper modal

app/views/users/index.html.haml
%h1 Listing users

%table#myTable.table-striped.display{:style => "width:100%"}
  %thead
    %tr
      %th user_id
      %th Email
      %th Name
      %th 
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user) 
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/main.html.haml
-#%p#notice= notice

-# frozen_string_literal: true
-#= simple_format(@user) do |f|
-#= f.error_notification
-#  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

-#  .form-inputs
-#    = f.input :email
-#    = f.input :password_digest

-#  .form-actions
/   = f.button :submit , "log in"
/   = f.button :register ,"register"

- flash.each do |type, msg|
  .alert.alert-danger{:role => "alert"}
    = msg
-#%p#notice= notice
-#%p.alert= alert

-#= simple_form_for(@user) do |form|
-#.d-flex.align-items-center.justify-content-center

.main
  = form_with do |form|
    .field
      -#=form.label :email 
      =form.text_field :email ,class:"form-control-lg w-100 m-3 shadow",placeholder: "Email"
      -#=form.label :password ,"password"
      =form.password_field :password ,class:"form-control-lg w-100 m-3 shadow",placeholder: "Password"
      .row
        .col
          = button_to "Log in" , "/main" ,class:"btn btn-primary ms-3 main-btn"
        .col
          = button_to "Register" , "/register",class:"btn btn-secondary ms-3 main-btn",method: "get"

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/profile.html.haml
- flash.each do |type, msg|
  .alert.alert-info
    = msg
= render 'nav'
%p{:style => "color:white;"}
  %strong Name:
  = @profile_user.name
%p{:style => "color:white;"} 
  %strong Email:
  = @profile_user.email
%br
- if @profile_user != @user
  - if @user.followees.include?(@profile_user)
    = button_to "Unfollow", unfollow_user_path , method: "POST",class:"btn btn-secondary main-btn"
  - else
    = button_to "Follow", follow_user_path , method: "POST" ,class:"btn btn-primary  main-btn"
= button_to "Back", "/feed" , method: "get" ,class:"btn btn-secondary main-btn mt-4"

%br
- @profile_user.posts.each do |post| 
  .card.mt-4{:style => "width: 50vw;"}
    .card-body.cardPost
      %h5.card-title= @profile_user.name
      %h6.card-subtitle.mb-2.text-muted= post.created_at.to_formatted_s(:short)
      %pCard.card-text.fst-italic= post.msg
      %br
      - if post.user_likes.include?(@user)
        = button_to "Unlike", unlike_post_path(post.id) , method: "POST",class:"btn btn-primary unlike-btn mt-2"
      - else
        = button_to "Like", like_post_path(post.id) , method: "POST" ,class:"btn btn-secondary  like-btn mt-2"
      - if post.likes.count != 0
        %button.btn.btn-primary.btn-showUser.mt-2.showUsers{"data-bs-target" => "#Like", "data-bs-toggle" => "modal", :type => "button","dataModal": post.user_likes.to_json}
          -#----------------number of like------------------
          = post.likes.count.to_s + " Likes"

.modal.fade{id: "Like","aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel",   :tabindex => "-1"}
  .modal-dialog.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h5#exampleModalLabel.w-100.modal-title.text-center ❤
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type  => "button"}
      .modal-body
        .div#mo_body{:style => "font-size:25px"}
        -#- post.user_likes.each do |user|
        -#  %a.card-link-feed{:href => "/profile/#{user.name}",:method => "get",:style => "-#font-size:25px"}
        -#    = user.name
        -#  %br
        -#  %br
:javascript
  $(".showUsers").click(function(){
    $("#mo_body").empty();
    var userJson = $(this).attr("dataModal");
    var userObject = jQuery.parseJSON(userJson);
    userObject.forEach((user) =>{
      //var link = document.createElement("a");
      var link = `<a class = "card-link-feed" href ="/profile/${user.name}"> ${user.name} </a> <br><br>`;
      $("#mo_body").append(link);   
    })
    var myModal = new bootstrap.Modal(document.getElementById(`Like`, {}));
  });

app/views/users/register.html.haml
%p#notice= notice

%h1.text-light Register User

= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :email ,class:"form-label",placeholder: 'Email'
    = f.input :name ,placeholder: 'Name'
    = f.input :password_digest, label: "Password",hint:'8-15 characters'
    = f.input :password_digest_confirmation, label: 'Password Confirmation'
  %br
  .d-flex.flex-row
    .form-actions.w-10.me-5
      = f.button :submit ,label: "OK" ,class: "btn btn-primary"
    %a.btn.btn-secondary{:href => "/main"}  Cancel

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Name:
  = @user.name
%p
  %b Password digest:
  = @user.password_digest

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path